name: Update Shaka Packager Cask

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  update-cask:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Check latest release version
      id: get_version
      run: |
        latest_version=$(curl --silent "https://api.github.com/repos/shaka-project/shaka-packager/releases/latest" | jq -r .tag_name | sed 's/^v//')
        echo "Latest version is $latest_version"
        echo "::set-output name=version::$latest_version"

    - name: Update Cask file
      run: |
        sed -i "s/version \".*\"/version \"${{ steps.get_version.outputs.version }}\"/" Casks/s/shaka-packager.rb
        latest_sha256=$(curl -L "https://github.com/shaka-project/shaka-packager/releases/download/v${{ steps.get_version.outputs.version }}/packager-osx-arm64" | shasum -a 256 | awk '{ print $1 }')
        sed -i "s/sha256 \".*\"/sha256 \"$latest_sha256\"/" Casks/s/shaka-packager.rb

    - name: Check for changes
      run: |
        git status
        git diff

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        if ! git diff --quiet; then
          git commit -am "Update shaka-packager to version ${{ steps.get_version.outputs.version }}"
          git push
        else
          echo "No changes detected, skipping commit."
        fi

